"""
===========================================================================
Project     : Autonomous AI Agent Platform
Module      : workflow_state.py

Description:
    Workflow state model.

Purpose:
    This module defines the WorkflowState model that represents the
    current state of an executing workflow.

Responsibilities:
    - Store workflow information
    - Track workflow status
    - Store user request
    - Store execution timestamps

Author      : Lokesh Kumar
Version     : v1.0.0
===========================================================================
"""

# ==========================================================================
# Standard Library Imports
# ==========================================================================

# Import date and time utilities.
from datetime import datetime

# ==========================================================================
# Third-Party Imports
# ==========================================================================

# Import Pydantic model support.
from pydantic import BaseModel

# Import field helper.
from pydantic import Field

# ==========================================================================
# Application Imports
# ==========================================================================

# Import workflow status constants.
from app.config.constants import WORKFLOW_CREATED

# ==========================================================================
# Workflow State Model
# ==========================================================================


class WorkflowState(BaseModel):
    """
    Represents the current state of a workflow.

    Every workflow executed by the platform will be represented
    using this model.
    """

    # ----------------------------------------------------------------------
    # Workflow Information
    # ----------------------------------------------------------------------

    # Unique workflow identifier.
    workflow_id: str

    # Current workflow status.
    workflow_status: str = WORKFLOW_CREATED

    # Original user request.
    user_request: str

    # Workflow creation timestamp.
    created_at: datetime = Field(default_factory=datetime.now)

    # ----------------------------------------------------------------------
    # Knowledge
    # ----------------------------------------------------------------------

    # Knowledge gathered by the Knowledge Agent.
    knowledge: str = ""

    # ----------------------------------------------------------------------
    # Planning
    # ----------------------------------------------------------------------

    # Execution plan generated by the Planning Agent.
    plan: str = ""

    # ----------------------------------------------------------------------
    # Research
    # ----------------------------------------------------------------------

    # Research summary generated by the Research Agent.
    research: str = ""

    # ----------------------------------------------------------------------
    # Review
    # ----------------------------------------------------------------------

    # Review generated by the Reviewer Agent.
    review: str = ""

    # ----------------------------------------------------------------------
    # Execution
    # ----------------------------------------------------------------------

    # Final execution result generated by the Execution Agent.
    execution_result: str = ""

    # ----------------------------------------------------------------------
    # Agent Information
    # ----------------------------------------------------------------------

    # Currently active agent.
    active_agent: str = ""

    # ----------------------------------------------------------------------
    # Execution Result
    # ----------------------------------------------------------------------

    # Final workflow response.
    final_response: str = ""


# ==========================================================================
# End of File
# ==========================================================================